2025-03-17 12:09:23,417 - __main__ - INFO - Using Telegram token: 7805196670...
2025-03-17 12:09:23,465 - __main__ - INFO - Starting bot. Output directory: generated
2025-03-17 12:09:24,325 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getMe "HTTP/1.1 200 OK"
2025-03-17 12:09:24,593 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/deleteWebhook "HTTP/1.1 200 OK"
2025-03-17 12:09:24,595 - telegram.ext.Application - INFO - Application started
2025-03-17 12:09:35,444 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:09:45,728 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:09:47,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:09:48,284 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:09:53,382 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:09:53,392 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:09:55,307 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:10:04,511 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:10:14,903 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:10:25,186 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:10:35,477 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:10:45,830 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:10:56,178 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:06,515 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:16,858 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:27,146 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:37,439 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:47,739 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:11:58,131 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:08,474 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:18,914 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:26,769 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:26,793 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:12:33,695 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:12:43,500 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:51,641 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:12:52,689 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:13:01,933 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:13:12,210 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:13:22,489 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:13:32,772 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:13:43,052 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:13:53,326 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:03,670 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:13,939 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:24,254 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:34,600 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:44,940 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:14:55,211 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:05,523 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:15,829 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:26,215 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:36,503 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:46,771 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:15:57,044 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:07,315 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:17,594 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:27,866 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:38,138 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:48,404 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:16:58,691 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:17:08,973 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:17:19,239 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:17:29,512 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:17:39,781 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:17:50,084 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:00,352 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:10,625 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:20,906 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:31,186 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:41,461 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:18:51,743 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:02,011 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:12,282 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:22,567 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:32,840 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:43,129 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:19:53,406 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:04,174 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:14,447 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:24,715 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:35,035 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:45,307 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:20:55,639 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:05,920 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:16,191 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:26,561 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:36,840 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:47,119 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:21:57,491 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:07,768 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:18,071 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:28,364 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:38,634 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:48,908 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:22:59,239 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:09,510 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:11,079 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:19,191 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:20,315 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:23:28,151 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:29,203 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:23:31,663 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:31,678 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:23:32,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:23:34,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:23:34,995 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:23:40,972 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:23:50,152 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:00,424 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:10,708 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:21,054 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:31,338 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:41,638 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:24:51,906 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:02,176 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:12,449 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:22,722 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:32,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:43,282 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:25:53,550 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:03,826 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:14,099 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:24,370 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:34,648 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:44,930 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:26:55,198 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:05,513 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:15,967 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:26,237 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:36,514 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:46,892 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:27:57,329 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:07,659 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:17,927 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:28,194 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:38,465 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:48,751 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:28:59,027 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:29:09,295 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:29:19,561 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:29:30,443 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:29:40,721 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:29:51,082 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:01,369 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:11,665 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:21,949 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:32,228 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:42,507 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:30:52,788 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:03,100 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:13,383 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:23,724 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:34,100 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:44,386 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:31:54,706 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:04,986 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:15,365 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:25,659 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:35,943 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:46,228 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:32:56,529 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:06,807 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:17,110 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:27,395 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:37,687 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:47,966 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:33:58,282 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:34:08,561 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:34:18,862 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:34:29,140 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:34:39,652 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:34:49,930 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:00,224 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:10,501 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:20,813 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:31,101 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:41,399 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:35:51,680 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:01,966 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:12,261 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:22,564 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:32,848 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:43,131 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:36:53,490 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:37:03,778 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:37:11,247 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:11,252 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:37:16,937 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:16,939 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:37:23,590 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:23,591 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:37:31,680 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:31,681 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:37:39,053 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:39,053 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:37:51,146 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:37:51,147 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:38:08,097 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:38:08,098 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:38:24,725 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:38:24,730 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:38:52,785 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:39:03,124 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:39:13,413 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:39:23,064 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:39:23,067 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:39:28,638 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:39:28,642 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:39:35,321 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:39:35,321 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:39:43,392 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:39:43,396 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:39:50,743 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:39:50,744 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:40:02,606 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:40:02,607 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:40:19,814 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:40:19,816 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:40:36,404 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:40:36,405 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:40:58,673 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:40:58,674 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:41:29,492 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:41:29,495 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:42:04,799 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:42:04,800 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:42:39,458 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:42:39,460 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:10,333 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:43:11,363 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:43:13,821 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:13,822 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:16,021 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:43:16,034 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:43:18,267 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:43:19,624 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 200 OK"
2025-03-17 12:43:19,627 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-03-17 12:43:23,412 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/sendMessage "HTTP/1.1 200 OK"
2025-03-17 12:43:26,372 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:26,373 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:31,944 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:31,946 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:38,072 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:38,072 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:45,392 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:45,394 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:43:52,528 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:43:52,528 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:44:04,702 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:44:04,704 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-17 12:44:17,534 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7805196670:AAF-WyK2KzjEmPBO_R2HfeOjFrSNN0gPwuc/getUpdates "HTTP/1.1 409 Conflict"
2025-03-17 12:44:17,537 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_updater.py", line 376, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 658, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 4605, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 691, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 362, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/_bot.py", line 720, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/bellacahya/AutoPDF/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
